Name: Aryan Shukla\
Roll No: 25/AFI/10

### Experiment 1 : Fundamentals of Tensor Operations using PyTorch and NumPy


In [11]:
import torch # Import the torch library for PyTorch
import numpy as np # Import the numpy library for NumPy

# NumPy arrays
np_1d = np.array([1, 2, 3]) # 1D NumPy array
np_2d = np.array([[1, 2], [3, 4]]) # 2D NumPy array
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D NumPy array

# PyTorch tensors
torch_1d = torch.tensor([1, 2, 3]) # 1D PyTorch tensor
torch_2d = torch.tensor([[1, 2], [3, 4]]) # 2D PyTorch tensor
torch_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D PyTorch tensor

print("1D NumPy array:\n", np_1d)
print("2D NumPy array:\n", np_2d)
print("3D NumPy array:\n", np_3d)
print("\n")
print("\n1D PyTorch tensor:\n", torch_1d)
print("2D PyTorch tensor:\n", torch_2d)
print("3D PyTorch tensor:\n", torch_3d)

1D NumPy array:
 [1 2 3]
2D NumPy array:
 [[1 2]
 [3 4]]
3D NumPy array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



1D PyTorch tensor:
 tensor([1, 2, 3])
2D PyTorch tensor:
 tensor([[1, 2],
        [3, 4]])
3D PyTorch tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [10]:


np_add = np_2d + np_2d
print("NumPy Element-wise Addition:\n", np_add)


np_subtract = np_2d - np_2d
print("NumPy Element-wise Subtraction:\n", np_subtract)


np_multiply = np_2d * np_2d
print("NumPy Element-wise Multiplication:\n", np_multiply)


np_divide = np_2d / np_2d
print("NumPy Element-wise Division:\n", np_divide)


print("\n")
torch_add = torch_2d + torch_2d
print("PyTorch Element-wise Addition:\n", torch_add)


torch_subtract = torch_2d - torch_2d
print("PyTorch Element-wise Subtraction:\n", torch_subtract)


torch_multiply = torch_2d * torch_2d
print("PyTorch Element-wise Multiplication:\n", torch_multiply)


torch_divide = torch_2d / torch_2d
print("PyTorch Element-wise Division:\n", torch_divide)

NumPy Element-wise Addition:
 [[2 4]
 [6 8]]
NumPy Element-wise Subtraction:
 [[0 0]
 [0 0]]
NumPy Element-wise Multiplication:
 [[ 1  4]
 [ 9 16]]
NumPy Element-wise Division:
 [[1. 1.]
 [1. 1.]]


PyTorch Element-wise Addition:
 tensor([[2, 4],
        [6, 8]])
PyTorch Element-wise Subtraction:
 tensor([[0, 0],
        [0, 0]])
PyTorch Element-wise Multiplication:
 tensor([[ 1,  4],
        [ 9, 16]])
PyTorch Element-wise Division:
 tensor([[1., 1.],
        [1., 1.]])


In [9]:

# NumPy dot product for 1D arrays
np_dot_product = np.dot(np_1d, np_1d)
print("NumPy Dot Product (1D arrays):", np_dot_product)

# NumPy matrix multiplication for 2D arrays
np_matrix_mult = np.matmul(np_2d, np_2d)
print("NumPy Matrix Multiplication (2D arrays):\n", np_matrix_mult)

print("\n")
# PyTorch dot product for 1D tensors
torch_dot_product = torch.dot(torch_1d, torch_1d)
print("PyTorch Dot Product (1D tensors):", torch_dot_product)


# PyTorch matrix multiplication for 2D tensors
torch_matrix_mult = torch.matmul(torch_2d, torch_2d)
print("PyTorch Matrix Multiplication (2D tensors):\n", torch_matrix_mult)

NumPy Dot Product (1D arrays): 14
NumPy Matrix Multiplication (2D arrays):
 [[ 7 10]
 [15 22]]


PyTorch Dot Product (1D tensors): tensor(14)
PyTorch Matrix Multiplication (2D tensors):
 tensor([[ 7, 10],
        [15, 22]])


In [6]:

# Accessing the element
np_1d_indexed = np_1d[1]
print("NumPy 1D Indexing (second element):", np_1d_indexed)

# Slicing
np_2d_sliced_row = np_2d[0, :]
print("NumPy 2D Slicing (first row):", np_2d_sliced_row)

# Accessing a specific element
np_2d_indexed_element = np_2d[0, 1]
print("NumPy 2D Indexing (element at [0,1]):", np_2d_indexed_element)

# Boolean masking
np_2d_masked = np_2d[np_2d > 2]
print("NumPy 2D Boolean Masking (elements > 2):", np_2d_masked)

# Extracting a subtensor
np_3d_subtensor = np_3d[0]
print("NumPy 3D Subtensor (first 2D slice):\n", np_3d_subtensor)

print("\n")
# Accessing the element
torch_1d_indexed = torch_1d[1]
print("PyTorch 1D Indexing (second element):", torch_1d_indexed)

# Slicing
torch_2d_sliced_row = torch_2d[0, :]
print("PyTorch 2D Slicing (first row):", torch_2d_sliced_row)

# Accessing a specific element
torch_2d_indexed_element = torch_2d[0, 1]
print("PyTorch 2D Indexing (element at [0,1]):", torch_2d_indexed_element)

# Boolean masking
torch_2d_masked = torch_2d[torch_2d > 2]
print("PyTorch 2D Boolean Masking (elements > 2):", torch_2d_masked)

# Extracting a subtensor
torch_3d_subtensor = torch_3d[0]
print("PyTorch 3D Subtensor (first 2D slice):\n", torch_3d_subtensor)


NumPy 1D Indexing (second element): 2
NumPy 2D Slicing (first row): [1 2]
NumPy 2D Indexing (element at [0,1]): 2
NumPy 2D Boolean Masking (elements > 2): [3 4]
NumPy 3D Subtensor (first 2D slice):
 [[1 2]
 [3 4]]


PyTorch 1D Indexing (second element): tensor(2)
PyTorch 2D Slicing (first row): tensor([1, 2])
PyTorch 2D Indexing (element at [0,1]): tensor(2)
PyTorch 2D Boolean Masking (elements > 2): tensor([3, 4])
PyTorch 3D Subtensor (first 2D slice):
 tensor([[1, 2],
        [3, 4]])


In [8]:

np_reshaped = np_2d.reshape(-1) # Reshape 2D NumPy array to 1D
print("NumPy Reshaped (1D):", np_reshaped)

# Transpose np_2d
np_transposed = np_2d.T
print("NumPy Transposed:\n", np_transposed)
print("\n")

torch_reshaped = torch_2d.view(-1) # Reshape 2D tensor to 1D
print("PyTorch Reshaped (1D):", torch_reshaped)

torch_transposed = torch_2d.T # Transpose 2D tensor
print("PyTorch Transposed:\n", torch_transposed)

NumPy Reshaped (1D): [1 2 3 4]
NumPy Transposed:
 [[1 3]
 [2 4]]


PyTorch Reshaped (1D): tensor([1, 2, 3, 4])
PyTorch Transposed:
 tensor([[1, 3],
        [2, 4]])


In [12]:

# Reshape torch_2d into (1, 4)
torch_reshaped_1_4 = torch.reshape(torch_2d, (1, 4))
print("PyTorch Reshaped (1,4):\n", torch_reshaped_1_4)

# Add a new dimension to torch_1d at position 0 using unsqueeze(0)
torch_1d_unsqueeze_0 = torch_1d.unsqueeze(0)
print("PyTorch unsqueeze(0) on 1D tensor:\n", torch_1d_unsqueeze_0)

# Add a new dimension to torch_1d at position 1 using unsqueeze(1)
torch_1d_unsqueeze_1 = torch_1d.unsqueeze(1)
print("PyTorch unsqueeze(1) on 1D tensor:\n", torch_1d_unsqueeze_1)

# Create a PyTorch tensor with singleton dimensions (e.g., (1,3,1))
torch_with_singletons = torch_1d.unsqueeze(0).unsqueeze(-1)
print("PyTorch tensor with singleton dimensions:\n", torch_with_singletons)

# Remove singleton dimensions from the tensor using squeeze()
torch_squeezed = torch_with_singletons.squeeze()
print("PyTorch squeezed tensor:\n", torch_squeezed)


# Reshape np_2d into (1, 4) using np.reshape()
np_reshaped_1_4 = np.reshape(np_2d, (1, 4))
print("NumPy Reshaped (1,4):\n", np_reshaped_1_4)

PyTorch Reshaped (1,4):
 tensor([[1, 2, 3, 4]])
PyTorch unsqueeze(0) on 1D tensor:
 tensor([[1, 2, 3]])
PyTorch unsqueeze(1) on 1D tensor:
 tensor([[1],
        [2],
        [3]])
PyTorch tensor with singleton dimensions:
 tensor([[[1],
         [2],
         [3]]])
PyTorch squeezed tensor:
 tensor([1, 2, 3])
NumPy Reshaped (1,4):
 [[1 2 3 4]]


In [13]:

# Reshape torch_2d into a 1D tensor using view(-1)
torch_view_1d = torch_2d.view(
    -1
)
print("PyTorch Reshaped (1D) using view():", torch_view_1d)

PyTorch Reshaped (1D) using view(): tensor([1, 2, 3, 4])


In [14]:

# Add a scalar to a 2D NumPy array
np_broadcast_scalar = np_2d + 10
print("NumPy Broadcasting (scalar addition):\n", np_broadcast_scalar)

# Add a 1D NumPy array to a 2D NumPy array
np_1d_broadcast = np.array([10, 20])
np_broadcast_1d = np_2d + np_1d_broadcast
print("NumPy Broadcasting (1D array addition):\n", np_broadcast_1d)

print("\n--- PyTorch Broadcasting Operations ---")
# Add a scalar to a 2D PyTorch tensor
torch_broadcast_scalar = torch_2d + 10
print("PyTorch Broadcasting (scalar addition):\n", torch_broadcast_scalar)

# Add a 1D PyTorch tensor to a 2D PyTorch tensor
torch_1d_broadcast = torch.tensor([10, 20])
torch_broadcast_1d = torch_2d + torch_1d_broadcast
print("PyTorch Broadcasting (1D tensor addition):\n", torch_broadcast_1d)

NumPy Broadcasting (scalar addition):
 [[11 12]
 [13 14]]
NumPy Broadcasting (1D array addition):
 [[11 22]
 [13 24]]

--- PyTorch Broadcasting Operations ---
PyTorch Broadcasting (scalar addition):
 tensor([[11, 12],
        [13, 14]])
PyTorch Broadcasting (1D tensor addition):
 tensor([[11, 22],
        [13, 24]])


In [15]:

# Create a copy out of place
np_out_of_place_arr = np_2d.copy()

np_result_out_of_place = np_out_of_place_arr + 1
print("NumPy Out-of-place Addition:\n", np_result_out_of_place)
print("NumPy Out-of-place Addition (Original unchanged):\n", np_out_of_place_arr)

# Create a copy for in-place demonstration
np_in_place_arr = np_2d.copy()
# Perform an in-place addition (modifies the original array)
np_in_place_arr += 1
print("NumPy In-place Addition (Modified original):\n", np_in_place_arr)


# Create a copy for out-of-place demonstration
torch_out_of_place_tensor = torch_2d.clone()
torch_result_out_of_place = torch_out_of_place_tensor + 1
print("PyTorch Out-of-place Addition (Result):\n", torch_result_out_of_place)
print("PyTorch Out-of-place Addition (Original unchanged):\n", torch_out_of_place_tensor)

# Create a copy for in-place demonstration
torch_in_place_tensor = torch_2d.clone()

torch_in_place_tensor.add_(1)
print("PyTorch In-place Addition (Modified original):\n", torch_in_place_tensor)

NumPy Out-of-place Addition:
 [[2 3]
 [4 5]]
NumPy Out-of-place Addition (Original unchanged):
 [[1 2]
 [3 4]]
NumPy In-place Addition (Modified original):
 [[2 3]
 [4 5]]
PyTorch Out-of-place Addition (Result):
 tensor([[2, 3],
        [4, 5]])
PyTorch Out-of-place Addition (Original unchanged):
 tensor([[1, 2],
        [3, 4]])
PyTorch In-place Addition (Modified original):
 tensor([[2, 3],
        [4, 5]])
